server:
  port: 8003
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
aliyun:
  vod:
    file:
      keyid: LTAI4FvvVEWiTJ3GNJJqJnk7
      keysecret: 9st82dv7EvFk9mTjYO1XXbM632fRbG

